######################################################################
# Automatically generated by qmake (3.1) Fri Nov 20 22:59:20 2020
######################################################################

TEMPLATE = subdirs

# Directories

SUBDIRS = core \
          gui \
          uci

core.subdir = src/core
gui.subdir = src/gui
uci.subdir = src/uci

gui.depends = core
